version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    healthcheck:
      test: bash -c "</dev/tcp/nginx/80&& exit 0 || exit 1"
      interval: 3s
      timeout: 30s
      retries: 10
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
      - ./_docker/php-fpm.d/www.conf:/usr/local/etc/www.conf
    container_name: project_app
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=paindetect
      - MYSQL_ROOT_PASSWORD=root
    container_name: project_db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    container_name: project_phpmyadmin
